### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by cjmabry** [With-the-Ranks/withtheranks-astro#2]
We need a good 404 page. Something that represents the amalgamation of great people we've assembled to work on fun stuff. What will it be?

Some inspo:
- https://berniesanders.com/404/
- https://www.tacobell.com/404 (h/t Aashish!)

**Comment by ajohn25** [comment]
Also reproduced the mobile version for some increased inspiration 🌮 
![image](https://github.com/With-the-Ranks/withtheranks-astro/assets/76596635/e1a24601-0063-46a4-bd67-c06b3c48e2b2)
