### ISSUE TITLE
Add a "docs" section

### ISSUE THREAD

**Issue by ajohn25** [With-the-Ranks/withtheranks-astro#8]
Our docs can live on this site since we have good support for Markdown. Share specific docs you'd like to bring in below!

**Comment by ajohn25** [comment]
Starting with https://docs.spokerewired.com

**Comment by cjmabry** [comment]
@ajohn25 do you think it'd be worthwhile to write a scraper of some sort to convert pages to Markdown or should we just split up stuff amongst ourselves?

**Comment by ajohn25** [comment]
> @ajohn25 do you think it'd be worthwhile to write a scraper of some sort to convert pages to Markdown or should we just split up stuff amongst ourselves?

I actually whipped up https://github.com/ajohn25/helpscout-docs-download for this already! Help Scout gives us the doc text as HTML already so it's even easier than expected 🎉

**Comment by cjmabry** [comment]
Amazing!
